(()=>{const canvas=document.querySelector('#bird-earth');if(!canvas)return;const ctx=canvas.getContext('2d');const wrap=canvas.parentElement;const status=document.querySelector('#earth-status');const buttons=[...document.querySelectorAll('[data-earth-region]')];let width=0,height=0,radius=0,scale=1,rotation=-155,tilt=-12,dragging=false,lastX=0,lastY=0,active='all',frame;
const lands=[[[ -168,72],[-125,72],[-52,48],[-82,8],[-116,20],[-168,55]],[[ -82,12],[-35,-5],[-52,-55],[-75,-50],[-81,-5]],[[ -12,72],[45,72],[82,55],[145,52],[178,68],[170,8],[116,4],[78,25],[48,10],[28,34],[-10,36]],[[ -18,34],[48,31],[52,-35],[17,-35],[-10,5]],[[112,-10],[154,-12],[151,-44],[115,-36]],[[ -180,-68],[180,-68],[180,-88],[-180,-88]]];
function inside(point,poly){let hit=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if((a[1]>point[1])!==(b[1]>point[1])&&point[0]<(b[0]-a[0])*(point[1]-a[1])/(b[1]-a[1])+a[0])hit=!hit}return hit}
const landDots=[];for(let lat=-86;lat<=84;lat+=4)for(let lon=-180;lon<180;lon+=4/Math.max(.3,Math.cos(lat*Math.PI/180)))if(lands.some(poly=>inside([lon,lat],poly)))landDots.push([lon,lat]);
function project(lon,lat){const la=lat*Math.PI/180,lo=(lon+rotation)*Math.PI/180,ti=tilt*Math.PI/180;const x=Math.cos(la)*Math.sin(lo),y=Math.sin(la)*Math.cos(ti)-Math.cos(la)*Math.cos(lo)*Math.sin(ti),z=Math.sin(la)*Math.sin(ti)+Math.cos(la)*Math.cos(lo)*Math.cos(ti);return{x:width/2+x*radius*scale,y:height/2-y*radius*scale,z}}
function line(points,color,weight=1){ctx.beginPath();let drawing=false;points.forEach(([lon,lat])=>{const p=project(lon,lat);if(p.z>0){drawing?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);drawing=true}else drawing=false});ctx.strokeStyle=color;ctx.lineWidth=weight;ctx.stroke()}
function regionBand(min,max,color){for(let lat=min;lat<=max;lat+=4){const pts=[];for(let lon=-180;lon<=180;lon+=4)pts.push([lon,lat]);line(pts,color,1.5)}for(let lon=-180;lon<180;lon+=12){const pts=[];for(let lat=min;lat<=max;lat+=2)pts.push([lon,lat]);line(pts,color,.55)}}
function draw(){ctx.clearRect(0,0,width,height);ctx.beginPath();ctx.arc(width/2,height/2,radius*scale,0,Math.PI*2);ctx.fillStyle='#071c26';ctx.fill();ctx.strokeStyle='#dce8e5';ctx.lineWidth=1.3;ctx.stroke();if(active==='all'||active==='south')regionBand(-67,-28,'rgba(236,104,75,.35)');if(active==='all'||active==='north')regionBand(22,52,'rgba(200,218,105,.35)');if(active==='all'||active==='equator')regionBand(-8,8,'rgba(115,183,199,.48)');for(let lat=-60;lat<=60;lat+=30){const pts=[];for(let lon=-180;lon<=180;lon+=4)pts.push([lon,lat]);line(pts,'rgba(216,228,223,.15)')};for(let lon=-150;lon<180;lon+=30){const pts=[];for(let lat=-88;lat<=88;lat+=3)pts.push([lon,lat]);line(pts,'rgba(216,228,223,.13)')};landDots.forEach(([lon,lat])=>{const p=project(lon,lat);if(p.z<=0)return;ctx.beginPath();ctx.arc(p.x,p.y,1.25*Math.max(.75,scale),0,Math.PI*2);ctx.fillStyle=`rgba(216,228,223,${.42+p.z*.5})`;ctx.fill()})}
function resize(){const box=wrap.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);width=box.width;height=box.height;radius=Math.min(width,height)*.405;canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw()}new ResizeObserver(resize).observe(wrap);
function animate(){if(!dragging&&!matchMedia('(prefers-reduced-motion: reduce)').matches){rotation+=.055;draw()}frame=requestAnimationFrame(animate)}
canvas.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging)return;rotation+=(e.clientX-lastX)*.35;tilt=Math.max(-70,Math.min(70,tilt-(e.clientY-lastY)*.25));lastX=e.clientX;lastY=e.clientY;draw()});canvas.addEventListener('pointerup',()=>dragging=false);canvas.addEventListener('pointercancel',()=>dragging=false);canvas.addEventListener('wheel',e=>{e.preventDefault();scale=Math.max(.68,Math.min(1.28,scale*(e.deltaY>0?.92:1.08)));draw()},{passive:false});
buttons.forEach(button=>button.addEventListener('click',()=>{active=button.dataset.earthRegion;buttons.forEach(item=>item.classList.toggle('active',item===button));if(active==='south'){tilt=32;rotation=-20;status.textContent='Southern Hemisphere · 18 profiles'}if(active==='north'){tilt=-28;rotation=-150;status.textContent='North Pacific · 3 profiles'}if(active==='equator'){tilt=0;rotation=90;status.textContent='Equatorial Pacific · Waved Albatross'}draw()}));resize();animate();window.addEventListener('pagehide',()=>cancelAnimationFrame(frame),{once:true})})();
